### ISSUE TITLE
Doesn't work with Ubuntu 22.04

### ISSUE THREAD

**Issue by msrd0** [WtfJoke/setup-tectonic#206]
I'm using inkscape to convert svg to tex so I need Ubuntu 22.04 for a recent inkscape version in CI. However, tectonic then fails to run with error message

```
tectonic myfile.tex
dlopen(): error loading libfuse.so.2

AppImages require FUSE to run. 
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
make: *** [Makefile:28: myfile.pdf] Error 1
```

**Comment by WtfJoke** [comment]
Hi @msrd0 

Thanks for reporting the issue.
This is an upstream issue of AppImage (https://github.com/AppImage/AppImageKit/issues/1120 https://github.com/AppImage/AppImageKit/issues/877) / Ubuntu 22.04 ([Bug 1965636](https://bugs.launchpad.net/ubuntu/+source/lubuntu-meta/+bug/1965636) marked as wont fixed in Ubuntu) . 

Have you tried installing libfuse like described in the link?
e.g.
```bash
sudo add-apt-repository universe
sudo apt install libfuse2
```


Probably this will be fixed upstream in AppImage with this issue https://github.com/AppImage/AppImageKit/issues/877

**Comment by msrd0** [comment]
Yes the workaround works. Unfortunately I'm stuck with texlive (which takes forever to install) since tectonic doesn't support pstricks which is what inkscape outputs.

**Comment by WtfJoke** [comment]
> Yes the workaround works.

🎉 

> I'm stuck with texlive (which takes forever to install) since tectonic doesn't support pstricks which is what inkscape outputs.

Thats a bummer :S
